/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Usuario
 */
public class PreguntaPanel extends javax.swing.JPanel {
    /**
     * Creates new form PreguntaPanel
     */
    public PreguntaPanel() {
        initComponents();
        
    
    RIncorrecta.setAlignmentX(Component.LEFT_ALIGNMENT); 
    lblPregunta.setFont(Utilidades.getRalewayFont(Font.PLAIN, 11));
    txtPregunta.setLineWrap(true);
    txtPregunta.setWrapStyleWord(true);
    txtPregunta.setFont(Utilidades.getRalewayFont(Font.BOLD, 12));
    txtPregunta.setMargin(new Insets(5, 8, 5, 8));
    
    txtCorrecta.setFont(Utilidades.getRalewayFont(Font.BOLD, 11));
    txtIncorrecta1.setFont(Utilidades.getRalewayFont(Font.BOLD, 11));
    txtIncorrecta2.setFont(Utilidades.getRalewayFont(Font.BOLD, 11));
    txtIncorrecta3.setFont(Utilidades.getRalewayFont(Font.BOLD, 11));
    
    txtCorrecta.setMargin(new Insets(3, 8, 3, 8));
    txtIncorrecta1.setMargin(new Insets(3, 8, 3, 8));
    txtIncorrecta2.setMargin(new Insets(3, 8, 3, 8));
    txtIncorrecta3.setMargin(new Insets(3, 8, 3, 8));

    RCorrecta.setAlignmentX(Component.LEFT_ALIGNMENT); 
    RCorrecta.setFont(Utilidades.getRalewayFont(Font.PLAIN, 11));
    RIncorrecta.setAlignmentX(Component.LEFT_ALIGNMENT); 
    RIncorrecta.setFont(Utilidades.getRalewayFont(Font.PLAIN, 11));
        
    Utilidades.SetImageLabel(lblEliminar, "src/resources/Menos_Off.png", new Dimension (15, 12));
    lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        // Cambia el icono a "Menos_On"
        Utilidades.SetImageLabel(lblEliminar, "src/resources/Menos_On.png", new Dimension(15, 12));
        
        // Elimina este panel del contenedor padre
        Container parent = PreguntaPanel.this.getParent();
        if (parent != null) {
            parent.remove(PreguntaPanel.this);
            parent.revalidate();
            parent.repaint();
            
            int preguntasRestantes = parent.getComponentCount();
            QuizGenerador.getInstancia().mostrarRegistro("Pregunta Eliminada (quedan " + preguntasRestantes + " preguntas restantes )");
        }
    }
});
   
    }
    
    
    
    public String getPregunta() { return txtPregunta.getText(); }
    public void setPregunta(String pregunta) { txtPregunta.setText(pregunta); }

    public String getRespuestaCorrecta() { return txtCorrecta.getText(); }
    public void setRespuestaCorrecta(String respuesta) { txtCorrecta.setText(respuesta); }

    public String getRespuestaIncorrecta1() { return txtIncorrecta1.getText(); }
    public void setRespuestaIncorrecta1(String respuesta) { txtIncorrecta1.setText(respuesta); }

    public String getRespuestaIncorrecta2() { return txtIncorrecta2.getText(); }
    public void setRespuestaIncorrecta2(String respuesta) { txtIncorrecta2.setText(respuesta); }

    public String getRespuestaIncorrecta3() { return txtIncorrecta3.getText(); }
    public void setRespuestaIncorrecta3(String respuesta) { txtIncorrecta3.setText(respuesta); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelOvalado();
        lblPregunta = new javax.swing.JLabel();
        txtPregunta = new TextAreaOvalado();
        RCorrecta = new javax.swing.JLabel();
        txtCorrecta = new TextFieldOvalado();
        lblEliminar = new javax.swing.JLabel();
        RIncorrecta = new javax.swing.JLabel();
        txtIncorrecta1 = new TextFieldOvalado();
        txtIncorrecta2 = new TextFieldOvalado();
        txtIncorrecta3 = new TextFieldOvalado();

        setBackground(new java.awt.Color(5, 19, 36));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        jPanel1.setBackground(new java.awt.Color(30, 43, 61));

        lblPregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPregunta.setText("Pregunta");

        txtPregunta.setBackground(new java.awt.Color(87, 99, 112));
        txtPregunta.setColumns(20);
        txtPregunta.setForeground(new java.awt.Color(255, 255, 255));
        txtPregunta.setRows(5);
        txtPregunta.setBorder(null);

        RCorrecta.setForeground(new java.awt.Color(255, 255, 255));
        RCorrecta.setText("Respuesta Correcta");

        txtCorrecta.setBackground(new java.awt.Color(87, 99, 112));
        txtCorrecta.setForeground(new java.awt.Color(255, 255, 255));
        txtCorrecta.setBorder(null);

        RIncorrecta.setForeground(new java.awt.Color(255, 255, 255));
        RIncorrecta.setText("Respuestas incorrectas");

        txtIncorrecta1.setBackground(new java.awt.Color(87, 99, 112));
        txtIncorrecta1.setForeground(new java.awt.Color(255, 255, 255));
        txtIncorrecta1.setBorder(null);

        txtIncorrecta2.setBackground(new java.awt.Color(87, 99, 112));
        txtIncorrecta2.setForeground(new java.awt.Color(255, 255, 255));
        txtIncorrecta2.setBorder(null);

        txtIncorrecta3.setBackground(new java.awt.Color(87, 99, 112));
        txtIncorrecta3.setForeground(new java.awt.Color(255, 255, 255));
        txtIncorrecta3.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIncorrecta3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIncorrecta1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCorrecta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(txtIncorrecta2))
                            .addComponent(RCorrecta)
                            .addComponent(RIncorrecta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RCorrecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RIncorrecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIncorrecta1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIncorrecta2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIncorrecta3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RCorrecta;
    private javax.swing.JLabel RIncorrecta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTextField txtCorrecta;
    private javax.swing.JTextField txtIncorrecta1;
    private javax.swing.JTextField txtIncorrecta2;
    private javax.swing.JTextField txtIncorrecta3;
    private javax.swing.JTextArea txtPregunta;
    // End of variables declaration//GEN-END:variables
}
