/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {
    private VistaSimulador vistaSimulador;
    private int gradoSeleccionado = 0; //Para almacenar el grado seleccionado
    
    /**
     * Creates new form Home
     */
    public Home() {
        setUndecorated(true);
        initComponents();
        escalaLauncherButtons();
        
        //Cargar JSON al iniciar
        String rutaJSON = "C:/Users/Usuario/Downloads/BaseDeDatos.json";
        LeerJSON.cargarJSON(rutaJSON);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                
            }
        });
        
        String imagePath = "FondoBase.png";
        Utilidades.setBackgroundImage(jPanel1, imagePath);
        jPanel1.setLayout(null);

        jPanel2.setBounds(305, 80, 1230, 90);
        content.setBounds(320, 210, 1200, 700);
        
        //panelnPanel e Inicializar la VistaSimulador
        vistaSimulador = new VistaSimulador();
        Utilidades.cambiarPanel(content, vistaSimulador);
        
        //listeners para los botones de grado 
        configurarLauncherButtons();
    
    }
    
    
    //Deberia Eliminarlo?
    private void escalaLauncherButtons() {
    Dimension originalSize = new Dimension(80, 80);

    for (int i = 0; i < 14; i++) {
        try {
            javax.swing.JLabel button = (javax.swing.JLabel) this.getClass().getDeclaredField("LauncherButton" + i).get(this);
            String ruta = "src/resources/LauncherButton" + i + ".png";
            
            Utilidades.SetImageLabel(button, ruta, originalSize);
            Utilidades.addHoverEffect(button, ruta, originalSize);
        } catch (NoSuchFieldException | IllegalAccessException e) {
           System.err.println("Error al escalar LauncherButton" + i + ":" + e.getMessage());
        }
    }
}
    
   private void configurarLauncherButtons() {
        // Configurar cada botón con su grado correspondiente
        for (int i = 0; i < 14; i++) {
            try {
                JLabel escudo = (JLabel) this.getClass().getDeclaredField("LauncherButton" + i).get(this);
                String rutaImagen = "src/resources/LauncherButton" + i + ".png";
                
                Utilidades.SetImageLabel(escudo, rutaImagen, new Dimension(80, 80));
                Utilidades.addHoverEffect(escudo, rutaImagen, new Dimension(80, 80));
                
                //Listener para abrir VistaSimulador con el Grado seleccionado
                final int gradoIndex = i; // Variable final para el listener
                escudo.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        // Actualizar la VistaSimulador con el nuevo grado
                        vistaSimulador.setGradoSeleccionado(gradoIndex);
                        //Cambiar al panel del simulador
                        Utilidades.cambiarPanel(content, vistaSimulador);
                    }
                });       
            } catch (Exception e) {
                System.err.println("Error al configurar botón LauncherButton" + i + ": " + e.getMessage());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LauncherButton0 = new javax.swing.JLabel();
        LauncherButton1 = new javax.swing.JLabel();
        LauncherButton2 = new javax.swing.JLabel();
        LauncherButton3 = new javax.swing.JLabel();
        LauncherButton4 = new javax.swing.JLabel();
        LauncherButton5 = new javax.swing.JLabel();
        LauncherButton6 = new javax.swing.JLabel();
        LauncherButton7 = new javax.swing.JLabel();
        LauncherButton8 = new javax.swing.JLabel();
        LauncherButton9 = new javax.swing.JLabel();
        LauncherButton10 = new javax.swing.JLabel();
        LauncherButton11 = new javax.swing.JLabel();
        LauncherButton12 = new javax.swing.JLabel();
        LauncherButton13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(1220, 700));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 14, 0, 10));
        jPanel2.add(LauncherButton0);
        jPanel2.add(LauncherButton1);
        jPanel2.add(LauncherButton2);
        jPanel2.add(LauncherButton3);
        jPanel2.add(LauncherButton4);
        jPanel2.add(LauncherButton5);
        jPanel2.add(LauncherButton6);
        jPanel2.add(LauncherButton7);
        jPanel2.add(LauncherButton8);
        jPanel2.add(LauncherButton9);
        jPanel2.add(LauncherButton10);
        jPanel2.add(LauncherButton11);
        jPanel2.add(LauncherButton12);
        jPanel2.add(LauncherButton13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LauncherButton0;
    private javax.swing.JLabel LauncherButton1;
    private javax.swing.JLabel LauncherButton10;
    private javax.swing.JLabel LauncherButton11;
    private javax.swing.JLabel LauncherButton12;
    private javax.swing.JLabel LauncherButton13;
    private javax.swing.JLabel LauncherButton2;
    private javax.swing.JLabel LauncherButton3;
    private javax.swing.JLabel LauncherButton4;
    private javax.swing.JLabel LauncherButton5;
    private javax.swing.JLabel LauncherButton6;
    private javax.swing.JLabel LauncherButton7;
    private javax.swing.JLabel LauncherButton8;
    private javax.swing.JLabel LauncherButton9;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}

