/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.json.JSONObject;
/**
 *
 * @author Usuario
 */
public class VistaSimulador extends javax.swing.JPanel {

    private int gradoSeleccionado = 0; // Almacena el indice del grado seleccionado y se actualiza con setGradoSeleccionado desde Home
     public void setGradoSeleccionado(int gradoIndex) {
        this.gradoSeleccionado = gradoIndex;
        configurarLabels();
    }
     
    /**
     * Creates new form VistaSimulador
     */
    public VistaSimulador() {
        initComponents();
        configurarLabels();
    }

    private void configurarLabels() {
        //Puede ser que cambie cada label de resources a getRutaImagen para que obtenga la ruta desde el LeerJSON?
    String[] temas = {"Grado0", "Grado1", "Grado2", "Grado3", "Grado4", "Grado5"};
    Dimension size = new Dimension(300, 250);
    
    for (int i = 0; i < 6; i++) {
        try {
            JLabel label = (JLabel) this.getClass().getDeclaredField("jLabel" + (i + 1)).get(this);
            String rutaImagen = "src/resources/" + temas[i] + ".png"; // Imagen del tema
            
            Utilidades.SetImageLabel(label, rutaImagen, size);
            Utilidades.addHoverEffect(label, rutaImagen, size);
            
            // Listener para abrir VistaGame con el juego correcto
            final int juegoIndex = i;
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    JSONObject juegoData = LeerJSON.getJuego(gradoSeleccionado, juegoIndex);
                    if (juegoData != null) {
                        JPanel parent = (JPanel) getParent();
                        System.out.println("Parent: " + parent);
                        Utilidades.cambiarPanel(parent, new VistaGame(juegoData));
                    }
                }
            });     
        } catch (Exception e) {
            System.err.println("Error al configurar label " + i + ": " + e.getMessage());
        }
    }
}

    
    private String getRutaImagen(int juegoIndex) {
        // Obtiene la ruta de la imagen para un juego específico desde el JSON
        JSONObject juegoData = LeerJSON.getJuego(gradoSeleccionado, juegoIndex);
        if (juegoData != null) {
            String nombreImagen = juegoData.optString("imagen","GradoDefault")+ ".png";
            String ruta = "src/resources/" + nombreImagen;
            
            if (new File(ruta).exists()) {
            return ruta;
        } else {
            System.err.println("No se encontró: " + ruta);
            return "src/resources/placeholder.png";
        }
    }
        return "src/resources/GradoDefault.png"; // Imagen por defecto si hay error
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new java.awt.GridLayout(2, 6, 40, 40));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel2);

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel3);

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4);

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5);

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
